env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode12.2
      script:
        - set -o pipefail
        - xcodebuild -project Tribute.xcodeproj -scheme "Tribute" -sdk macosx clean build
